### ISSUE TITLE
dialog med Konen

### ISSUE THREAD

**Issue by Bateia** [nilsmunch/SockMystery#10]
Hun ville da ikke tiltale sig selv _than his wife_ måske mere direkte?

**Comment by Lohardt** [comment]
Sted i BM:
https://branchmaker.com/nodes/3d0f9d90-62ec-11eb-817e-8b728a227200

Det er ok at hun taler om sig selv i 3. person. Det ligger vægt på at hun har følt sig tilsidesat. :)
